### ISSUE TITLE
Academy API

### ISSUE THREAD

**Issue by nghianv-1868** [tantv-918/certificate-verify#13]
- [ ] get all Subjects - GET /subjects 
- [ ] get all Students - GET /students (role : academy admin/ student admin)
- [ ] get all Teachers - GET /teachers (role : academy admin)
- [ ] get all Certificates - GET /certificates (role : academy admin)
- [ ] get teacher detail -  GET /teacher/:id (role : academy admin/teacher)
- [ ] register subject -  POST /subject  (role : academy admin) 
- [ ] get detail subject -  GET /subject/:id (role : academy admin/teacher) 
- [ ] set Scores -  POST /score (role : teacher)
- [ ] register teacher - POST /register (role : academy admin)

**Comment by conglt10** [comment]
Tôi thấy 1 số chỗ chưa hợp lý lắm @nghianv-1868 xem lại thử coi:
- get teacher detail nên là GET /teacher/:id
- register teacher, Issue #12 cũng có cái create teacher (mà student làm sao tạo teacher được) có vẻ 2 cái này trùng nhau.

**Comment by dotrungkien** [comment]
@nghianv-1868 
- để chữ thường
- ở các POST API e cần bổ sung thêm payload gửi lên là gì vào
- techer detail thì không phải là register -> chỉnh lại api route như comment của Công
- chưa có get subject đơn ? 
- get all scores chưa rõ ràng lắm ?

**Comment by conglt10** [comment]
get all Subjects - GET /subjects
 get all Students - GET /students (role : academy admin/ student admin)
 get all Certificates - GET /certificates (role : academy admin)
 register subject - POST /subject (role : academy admin)
 get detail subject - GET /subject/:id (role : academy admin/teacher)
 set Scores - POST /score (role : teacher)
