### ISSUE TITLE
Sign up/ Sign in

### ISSUE THREAD

**Issue by nghianv-1868** [tantv-918/certificate-verify#7]
Sign in - Sign up
- [ ] UI
  - [ ] content component
  - [ ] form sign up component
  - [ ] form sign in component
- [ ] Logic
  - [x] connect to blockchain by identity in wallet
  - [ ] set sesscion user
  - [ ] login basic by mongoDB with Vue

**Comment by conglt10** [comment]
tôi đang làm phần connect to blockchain by identity in wallet nhé
